{% set name = "sputnik" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sputnik-{{ version }}.tar.gz
  sha256: 2a2a506a2d68383f73dc7a546957714d316e23ce558e8d9115674f899d1f1273

build:
  number: 1003
  noarch: python
  entry_points:
    - sputnik = sputnik.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - semver

test:
  imports:
    - sputnik
    - sputnik.tests
  commands:
    - pip check
    - sputnik --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/explosion/sputnik
  license: MIT
  license_file: LICENSE
  summary: 'Sputnik: a data package manager library'
  description: |
    Sputnik is a library for managing data packages for another library, e.g.,
    models for a machine learning library.

extra:
  recipe-maintainers:
    - rmax
